project_identifier: neptune-web-components
files:
  - source: /packages/components/i18n/en.json
    translation: /packages/components/i18n/%two_letters_code%.%file_extension%
    update_option: update_as_unapproved
