name: 'size'
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - run: yarn setup
      - uses: andresz1/size-limit-action@v1.0.0
        with:
          directory: packages/components/
          github_token: ${{ secrets.GITHUB_TOKEN }}
